export const applications = [
  {
    id: 1,
    link: `http://app.advancetecllc.com/expense-report`,
    iconName: `request_quote`,
    title: `Expense Report`,
    description: `File your expenses`,
    enabled: true,
  },
  {
    id: 2,
    link: `http://app.advancetecllc.com/inventory`,
    iconName: `inventory`,
    title: `Inventory`,
    description: `View and manage warehouse stock`,
    enabled: false,
  },
  {
    id: 3,
    link: `http://app.advancetecllc.com/fabrication-tracker`,
    iconName: `construction`,
    title: `Fabrication Tracker`,
    description: `Manage delivery goals and track completion`,
    enabled: false,
  },
  {
    id: 4,
    link: `http://app.advancetecllc.com/safety-inspection`,
    iconName: `health_and_safety`,
    title: `Safety Inspection`,
    description: `Review procedures and record safety inspections`,
    enabled: false,
  },
  {
    id: 5,
    link: `http://app.advancetecllc.com/hours-report`,
    iconName: `work_history`,
    title: `Hours Report`,
    description: `Report hours worked on site`,
    enabled: false,
  },
  {
    id: 6,
    link: `http://app.advancetecllc.com/process-flowchart`,
    iconName: `account_tree`,
    title: `Process Flowchart`,
    description: `Review steps for different material types`,
    enabled: false,
  },
  {
    id: 7,
    link: `http://app.advancetecllc.com/unistrut-calculator`,
    iconName: `calculate`,
    title: `Unistrut Calculator`,
    description: `Calculate part quantities from strut connections`,
    enabled: false,
  },
]
