export const applications = [
  {
    id: 1,
    link: `http://expense-report.advancetecllc.com/`,
    iconName: `request_quote`,
    title: `Expense Report`,
    description: `File your expenses`,
    enabled: true,
  },
  {
    id: 2,
    link: `http://inventory.advancetecllc.com/`,
    iconName: `inventory`,
    title: `Inventory`,
    description: `View and manage warehouse stock`,
    enabled: false,
  },
  {
    id: 3,
    link: `http://fabrication-tracker.advancetecllc.com/`,
    iconName: `construction`,
    title: `Fabrication Tracker`,
    description: `Manage delivery goals and track completion`,
    enabled: false,
  },
  {
    id: 4,
    link: `http://safety-inspection.advancetecllc.com/`,
    iconName: `health_and_safety`,
    title: `Safety Inspection`,
    description: `Review procedures and record safety inspections`,
    enabled: false,
  },
  {
    id: 5,
    link: `http://process-flowchart.advancetecllc.com/`,
    iconName: `account_tree`,
    title: `Process Flowchart`,
    description: `Review steps for different material types`,
    enabled: false,
  },
  {
    id: 6,
    link: `http://unistrut-calculator.advancetecllc.com/`,
    iconName: `calculate`,
    title: `Unistrut Calculator`,
    description: `Calculate part quantities from strut connections`,
    enabled: false,
  },
]
